-- Users table mirrors the authenticated users from Supabase Auth.
create table if not exists public.users (
    id uuid primary key references auth.users(id) on delete cascade,
    email text unique not null,
    name text not null,
    avatar_url text,
    created_at timestamptz default now()
);

-- Tasks point to the user who created them and the user assigned to them.
create table if not exists public.tasks (
    id bigint generated by default as identity primary key,
    title text not null,
    description text default '',
    created_by uuid not null references public.users(id) on delete cascade,
    assigned_to uuid not null references public.users(id) on delete cascade,
    status text not null default 'pending' check (status in ('pending', 'completed')),
    created_at timestamptz default now(),
    completed_at timestamptz
);

create index if not exists tasks_created_by_idx on public.tasks(created_by);
create index if not exists tasks_assigned_to_idx on public.tasks(assigned_to);

-- This app uses the Flask backend for database access.
-- The service role key stays on the backend and is never exposed to the browser.
alter table public.users enable row level security;
alter table public.tasks enable row level security;
